import { execSync } from "node:child_process";
import { readFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "..");

const envPath = resolve(PROJECT_ROOT, ".env");
if (existsSync(envPath)) {
  for (const line of readFileSync(envPath, "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const sep = trimmed.indexOf("=");
    if (sep === -1) continue;
    const key = trimmed.slice(0, sep).trim();
    const val = trimmed.slice(sep + 1).trim();
    process.env[key] = val;
  }
}

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_OWNER = "giovanicavila";
const GITHUB_REPO = "imme";

function exec(cmd, opts = {}) {
  return execSync(cmd, { cwd: PROJECT_ROOT, encoding: "utf-8", ...opts }).trim();
}

function getCommits() {
  exec("git fetch origin");
  const log = exec("git log origin/main..origin/develop --oneline --no-decorate");
  if (!log) return [];
  return log.split("\n").map(line => {
    const match = line.match(/^(\S+)\s+(.*)/);
    return match ? { hash: match[1], message: match[2] } : { hash: "", message: line };
  });
}

async function github(method, path, body) {
  const url = `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}${path}`;
  const res = await fetch(url, {
    method,
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      "Content-Type": "application/json",
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "imme-merge-bot",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json();
  if (!res.ok && !Array.isArray(data)) {
    throw new Error(data.message || `GitHub API error (${res.status})`);
  }
  return data;
}

async function main() {
  try {
    const commits = getCommits();
    if (commits.length === 0) {
      console.log(JSON.stringify({ status: "noop", message: "Nothing to merge — develop is already up to date with main" }));
      return;
    }

    if (!GITHUB_TOKEN) {
      exec("git checkout main");
      exec("git pull origin main");
      exec("git merge origin/develop");
      exec("git push origin main");
      exec("git checkout develop");
      console.log(JSON.stringify({
        status: "merged_direct",
        message: `Merged ${commits.length} commit(s) directly (no GITHUB_TOKEN set)`,
        commits: commits.length,
      }));
      return;
    }

    const existingPRs = await github("GET", `/pulls?head=develop&base=main&state=open`);
    let prNumber, prUrl, prTitle;

    if (Array.isArray(existingPRs) && existingPRs.length > 0) {
      const existing = existingPRs[0];
      prNumber = existing.number;
      prUrl = existing.html_url;
      prTitle = existing.title;
      console.log(JSON.stringify({ status: "found_existing_pr", prNumber, prUrl, title: prTitle }));
    } else {
      prTitle = commits.length === 1
        ? commits[0].message
        : `Merge ${commits.length} changes from develop → main`;
      const commitLines = commits.map(c => `* ${c.message} (\`${c.hash.slice(0, 7)}\`)`);
      const prBody = `## Changes\n\n${commitLines.join("\n")}\n\n---\n🔀 Auto-generated by Telegram bot`;

      const pr = await github("POST", "/pulls", {
        title: prTitle,
        body: prBody,
        head: "develop",
        base: "main",
      });
      prNumber = pr.number;
      prUrl = pr.html_url;
      console.log(JSON.stringify({ status: "pr_created", prNumber, prUrl, title: prTitle }));
    }

    const mergeResult = await github("PUT", `/pulls/${prNumber}/merge`, {
      merge_method: "squash",
    });
    const merged = mergeResult.merged || false;

    if (merged) {
      exec("git checkout main");
      exec("git pull origin main");
      exec("git checkout develop");
      exec("git pull origin develop");

      console.log(JSON.stringify({
        status: "pr_merged",
        prNumber,
        prUrl,
        commits: commits.length,
        title: prTitle,
        commitList: commits.map(c => c.message),
        sha: mergeResult.sha,
      }));
    } else {
      console.log(JSON.stringify({
        status: "merge_conflict",
        prNumber,
        prUrl,
        message: mergeResult.message || "Merge conflict detected",
      }));
    }
  } catch (err) {
    console.error(JSON.stringify({ status: "error", message: err.message }));
    process.exit(1);
  }
}

main();
